Bug/89 blog page missing the label of form input
taodemy/website pull request #96
Opened 2023-03-02 07:55 UTC by Cameron933

### Descriptions
1. Added label for input in subscription section
2. Adjusted InfoBlock css for text line breaks

- Link to Zenhub Card: https://app.zenhub.com/workspaces/taodemy-63c3dec267d0df73ca6087cb/issues/gh/taodemy/website/89
- Link to UI design (if possible): no need

### Provide screenshots or videos that the function is working.
![image](https://user-images.githubusercontent.com/73293255/222365808-2752a4a1-f7af-4398-bf54-03bf0692da40.png)
![image](https://user-images.githubusercontent.com/73293255/222365943-6e1b68ae-5171-44a6-a45a-16daac8fb712.png)
![image](https://user-images.githubusercontent.com/73293255/222366060-71dfe8f3-1a6e-4246-982c-c34b8e1af386.png)

### Provide screenshots of no warning, or error in the console.
![image](https://user-images.githubusercontent.com/73293255/222366107-cfee572d-5547-4fef-8b06-eff7a337ff2a.png)

- [ ] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [ ] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [ ] Check PR title is aligned with your ticket.
- [ ] Check your app will run without crashes.
- [ ] Check if there are hard-coded values.
- [ ] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [ ] Check you are using `camelCase && PascalCase` correctly.
- [ ] Remove unused comments.

2023-03-03 05:26 UTC, HarryuCATGREY requested changes

2023-03-03 05:26 UTC, HarryuCATGREY commented on components/general/InfoBlock/InfoBlock.tsx
> +              </label>
One possible solution for keep label exist and hide it is put it outside the user view like follows:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/70834897/222638574-bc3ce703-5d64-4bc1-9a01-93c1e85e59ea.png">

2023-03-03 13:44 UTC, Cameron933 commented
> <img alt="image" width="235" src="https://user-images.githubusercontent.com/68804519/222624159-0ae6d06a-d667-4546-ae0f-9beee32446b4.png">
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/68804519/222624184-5e81707b-8cd3-47fe-92f9-3a08678ebf05.png">
> 
> I think it's different with the figma

![image](https://user-images.githubusercontent.com/73293255/222735463-3a4464d7-9579-448e-8644-fd812e541e8b.png)
![image](https://user-images.githubusercontent.com/73293255/222735502-95e25db5-d79c-40ee-8fb9-3dcf14bc347f.png)

2023-03-06 05:33 UTC, HarryuCATGREY approved these changes
LGTM

2023-03-06 07:09 UTC, jiayuu-u approved these changes
LGTM

2023-03-06 07:28 UTC, merged